# SwiftLint Configuration for KYCFlowApp
# This configuration is optimized for SwiftLintBuildToolPlugin

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import
  - capture_variable

# Paths to include
included:
  - KYCFlowApp
  - KYCFlowAppTests
  - KYCFlowAppUITests

# Paths to exclude
excluded:
  - ${DERIVED_DATA}
  - .build
  - .swiftpm
  - DerivedData
  - Pods
  - Carthage
  - fastlane
  - R.generated.swift
  - ${PODS_ROOT}
  - ${TARGET_TEMP_DIR}
  - ${DERIVED_FILES_DIR}

# Enabled opt-in rules
opt_in_rules:
  # Performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - last_where
  - reduce_boolean
  - reduce_into
  
  # Style
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_init
  - fallthrough
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  
  # Safety
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate
  
  # Code Quality
  - convenience_type
  - duplicate_imports
  - legacy_multiple
  - legacy_random
  - lower_acl_than_parent
  - nsobject_prefer_isequal
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - static_operator
  - unavailable_function
  - unowned_variable_capture
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - nesting
  - todo
  - type_body_length

# Rule configurations
force_cast: error
force_try: error
force_unwrapping: error

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - ID
    - URL
    - url
    - uri
    - URI
    - vm
    - vc
    - to
    - NL
    - US
    - DE
    - nl
    - us
    - de

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL

closure_body_length:
  warning: 30
  error: 50


private_outlet:
  allow_private_set: true

redundant_discardable_let:
  severity: warning

redundant_string_enum_value:
  severity: warning

switch_case_alignment:
  indented_cases: true

trailing_comma:
  mandatory_comma: false

unused_closure_parameter:
  severity: warning

unused_optional_binding:
  ignore_optional_try: false

# Custom Rules
custom_rules:
  avoid_print:
    included: ".*\\.swift"
    excluded: ".*Test\\.swift"
    name: "Avoid Print"
    regex: '^\s*print\('
    message: "print() should not be used in production code. Use proper logging instead."
    severity: warning
  
  mark_format:
    included: ".*\\.swift"
    name: "MARK Format"
    regex: '\/\/ MARK: -?[a-z]'
    message: "MARK should be followed by a capitalized word"
    severity: warning
  
  
  final_class:
    included: ".*\\.swift"
    excluded: ".*Test\\.swift"
    name: "Final Class"
    regex: '^class\s+(?!.*(final|open))'
    message: "Classes should be marked as final or explicitly open"
    severity: warning
  

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, markdown)
reporter: "xcode"